#define SERVER_NAME "Geebrox" //Название сервера
#define SERVER_MODE "Role Play" //Мод сервера
#define SERVER_LANGUAGE "Russian" //Язык сервера
#define SERVER_WEBSITE "null" //Сайт/Форум сервера


#define MYSQL_HOST "127.0.0.1" //Хост базы данных
#define MYSQL_USER "root" //Имя пользователя базы данных
#define MYSQL_PASS "" //Паролль от базы данных
#define MYSQL_BASE "geebrox" //Имя базы данных


#define COLOR_TITLE "{3498db}" //Цвет используемый для заголовок
#define COLOR_TEXT "{ecf0f1}" //Цвет используемый для обычных информаций
#define COLOR_NOTE "{e67e22}" //Цвет используемый для подчеркиваний важдных слов
#define COLOR_ERROR "{c0392b}" //Цвет используемый при ощибке
#define COLOR_SUCCESS "{2ecc71}" //Цвет используемый при успехе

#define HEX_COLOR_TITLE 0x3498dbFF
#define HEX_COLOR_TEXT 0xecf0f1FF
#define HEX_COLOR_NOTE 0xe67e22FF
#define HEX_COLOR_ERROR 0xc0392bFF
#define HEX_COLOR_SUCCESS 0x2ecc71FF