#define MAX_ADMIN_RANK_LENGTH 18 //Максимальная длина ранга администратора (не изменяйте, если не понимаете зачем это)
#define MAX_ADMIN_LOGIN_ATTEMPTS 2 //Кол-во попыток ввода админ пароля

#define COLOR_ADMIN_NOTE "{e67e22}" //Цвет уведомление для администраторов
#define HEX_COLOR_ADMIN_NOTE 0xe67e22FF //Цвет уведомление для администраторов

#define COLOR_ADMIN_CHAT "{7f8c8d}" //Цвет чата для администраторов
#define HEX_COLOR_ADMIN_CHAT 0x7f8c8dFF //Цвет чата для администраторов


//Найтройка уровни администраторов, чтобы использовать команду
#define CMD_admin 1
#define CMD_clearchat 1
#define CMD_kick 2
#define CMD_vehicle 3
#define CMD_ban 6